apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook-dep
  labels:
    app: storybook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storybook-app
  template:
    metadata:
      labels:
        app: storybook-app
    spec:
      containers:
      - name: storybook
        image: rafcasto/cryptoibero-storybook
        env:
        - name: NPM_TOKEN
          value: $NPM_TOKEN
        ports:
        - containerPort: 6006