apiVersion: v1
kind: Service
metadata:
  name: storybook-svc
  labels:
    app: storybook-app
spec:
  type: LoadBalancer 
  ports:
  - port: 6006
    targetPort: 6006
    protocol: TCP
  selector:
    app: storybook-app